name: Build

on: [push]

jobs:
  build-swift:
    name: Build with swift
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Package with swift
        run: swift build

  build-xcodebuild:
    name: Build with xcodebuild
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['schemes'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build Package with xcodebuild
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild -scheme $scheme  -destination 'platform=iOS Simulator,name=iPhone 13'
      - name: Build Example
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild clean build -project Example/Example.xcodeproj -scheme $scheme -sdk iphoneos
 
  cocoapods:
    name: Verify cocopods podspec
    needs: [ build-xcodebuild ]
    runs-on: macos-13
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'
      - name: Verify cocoapods
        run: pod lib lint --allow-warnings
