name: Build

on: [push]

jobs:
  build-swift:
    name: Build with swift
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Package with swift
        run: swift build

  build-xcodebuild:
    name: Build with xcodebuild
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Package with xcodebuild
        run: xcodebuild -scheme ApiVideoClient -destination 'platform=iOS Simulator,name=iPhone 16'
      - name: Build Example
        run: xcodebuild clean build -project Example/Example.xcodeproj -scheme ApiVideoClient -sdk iphoneos
 
  cocoapods:
    name: Verify cocopods podspec
    needs: [ build-xcodebuild ]
    runs-on: macos-13
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'
      - name: Verify cocoapods
        run: pod lib lint --allow-warnings
